//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdministratorSetting
    {
        public string mail { get; set; }
        public Nullable<System.DateTime> chatStart { get; set; }
        public Nullable<System.DateTime> chatEnd { get; set; }
    
        public virtual User User { get; set; }
    }
}
