//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThisDayContent
    {
        public System.DateTime date { get; set; }
        public int titleId { get; set; }
        public string content { get; set; }
    
        public virtual ThisDayOfGroup ThisDayOfGroup { get; set; }
    }
}
