//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstSample
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.Data.Entity;
    using System.Runtime.Serialization.Json;

    [Serializable]
    [DataContract]
    public class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users(string mail)
        {
            this.mail = mail;
            this.UserInGroups = new HashSet<UserInGroup>();
        }
        public Users()
        {
            
        }
        public Users(
            string mail,
            string firstName,
            string lastName,
            string childFirstName,
            string childLastName,
            string nickName,
            string profile,
            string password,
            string city,
            string streat
            )
        {
            this.mail = mail;
            this.firstName = firstName;
            this.lastName=lastName;
            this.childLastName=childFirstName;
            this.childLastName= childLastName;
            this.nickname= nickName;
            this.profile_= profile;
            this.password_=password;
            this.city=city;
            this.streat=streat;
            this.UserInGroups = new HashSet<UserInGroup>();
        }
        public Users(
           string mail,
           string firstName,
           string lastName,
           string childFirstName,
           string childLastName,
           string nickName,
           string profile,
           string password,
           string city,
           string streat,
           int build,
           string phone
           )
        {
            this.mail = mail;
            this.firstName = firstName;
            this.lastName = lastName;
            this.childLastName = childFirstName;
            this.childLastName = childLastName;
            this.nickname = nickName;
            this.profile_ = profile;
            this.password_ = password;
            this.city = city;
            this.streat = streat;
            this.build = build;
            this.UserInGroups = new HashSet<UserInGroup>();
        }
        
        [DataMember]
        public string firstName { get; set; }
        [DataMember]
        public string lastName { get; set; }
        [DataMember]
        public string childLastName { get; set; }
        [DataMember]
        public string nickname { get; set; }
        [DataMember]
        public string profile_ { get; set; }
        [DataMember]
        public string mail { get; set; }
        [DataMember]
        public string password_ { get; set; }
        [DataMember]
        public string city { get; set; }
        [DataMember]
        public string streat { get; set; }
        [DataMember]
        public Nullable<int> build { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<UserInGroup> UserInGroups { get; set; }
    }
}
