//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstSample
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.Data.Entity;

    [Serializable]
    [DataContract]
    public partial class UserInGroup
    {
        [DataMember]
        public int id { get; set; }
        [DataMember]
        public int groupId { get; set; }
        [DataMember]
        public string userMail { get; set; }
        [DataMember]
        public bool type_ { get; set; }
        [DataMember]
        public virtual Group Group { get; set; }
        [DataMember]
        public virtual Users User { get; set; }
        public UserInGroup(int groupId, string mail,bool type)
        {
            this.userMail = mail;
            this.groupId = groupId;
            this.type_ = type;
        }
        public UserInGroup()
        {
            
        }
    }
}


