//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInGroup
    {
        public string userMail { get; set; }
        public int groupId { get; set; }
        public bool isAdministrator { get; set; }
        public string childFirstName { get; set; }
        public string childLastName { get; set; }
        public string nickname { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
    }
}
